server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keshe3
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: tzkeshe3in2025KFC666Man8OuthJMdmLdHj8hYKlnOmjLmanBoyeLayElamaNbo88Amn4WcaosiNDemaNZKKnhmn
  expiration: 2592000000 # 30天